### PR TITLE
Uses nonblank card img if available

### PR DESCRIPTION
**Pull request by Zorgie**

### CODE REVIEW

**Comment by alexanderwiklund** [comment]
Please change `var` to `let` for consistency with the rest of the file, and before using `parsedBody.editions.length` you need to check that `parsedBody.editions` actually exists in the response (like the original guard code did) otherwise this might result in an exception.

This change will also reject all cards that don't contain an image; if the only image found is the default one (0.jpg) the if condition in the loop never passes, causing `imgLink.length` to be zero and trigger the guard on line 55.

**Comment by Zorgie** [comment]
lol nerd

**Comment by Zorgie** [comment]
PTAL

**Comment by Zorgie** [comment]
PTAL

**Pull request merged**
